# Generated by Django 2.2.7 on 2019-11-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_data', '0005_auto_20191116_2328'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_sem', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('no_class_week', models.IntegerField()),
                ('no_of_slots', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_data.Course')),
                ('teacher_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_data.Teacher')),
            ],
            options={
                'unique_together': {('branch_sem', 'course_code')},
            },
        ),
    ]
