# Generated by Django 2.2.7 on 2019-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse1_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse2_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse3_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse4_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse5_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse6_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse7_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('cse8_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece1_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece2_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece3_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece4_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece5_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece6_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece7_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('ece8_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it1_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it2_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it3_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it4_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it5_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it6_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it7_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('it8_faculty', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='cse1',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse2',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse3',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse4',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse5',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse6',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse7',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cse8',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece1',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece2',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece3',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece4',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece5',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece6',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece7',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='ece8',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it1',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it2',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it3',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it4',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it5',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it6',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it7',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='it8',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
