# Generated by Django 2.2.7 on 2019-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191120_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultteacher',
            options={'ordering': ['id']},
        ),
    ]
