# Generated by Django 2.2.7 on 2019-11-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191120_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['id']},
        ),
    ]
