# Generated by Django 2.2.7 on 2019-11-26 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191120_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_schema',
            field=models.IntegerField(default=2014, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
    ]
