# Generated by Django 2.2.7 on 2019-11-16 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_data.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('sem', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('course_intro', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(9999)])),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_data.Branch')),
            ],
        ),
    ]
