# Generated by Django 2.2.7 on 2019-11-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_data', '0004_auto_20191116_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('sem', 'course_code')},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('first_name',)},
        ),
    ]
