# Generated by Django 2.2.7 on 2019-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_data', '0005_auto_20191116_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
